# Search and replace the values below with the correct values for your app
app_name: MajorE App
launcher_name: MajorE App
package_name: majore_mvvm_template
description: "A new Flutter project."
bundle_id_android: com.majore.template
bundle_id_ios: com.majore.template
firebase_project_id_prod: majore-template
firebase_project_id_staging: majore-template
flutter_version: 3.32.0
