app_name: MajorE App
launcher_name: MajorE App
package_name: majore_mvvm_template
description: "A new Flutter project."
bundle_id_android: com.majore.app
bundle_id_ios: com.majore.app
firebase_project_id_prod: majore-template
firebase_project_id_staging: majore-template
flutter_version: 3.32.0
flutter_launcher_icons:
  image_path: "assets/images/launcher_icon.png"
  android: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
    icon_size: 48
  macos:
    generate: false

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true 