name: majore_mvvm_template
description: "A new Flutter project."
launcher_name: Shun App
bundle_id_android: com.shun.app
bundle_id_ios: com.shun.app
  
publish_to: 'none'
# The following defines the version and build number for your application using this format:version: 1.0.0-test+1
version: 1.0.0+1
environment:
  sdk: ^3.8.0


dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_analytics: ^11.6.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_remote_config: ^5.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_env_native: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  http_parser: ^4.1.2
  intl: ^0.20.2
  logging: ^1.3.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5
  riverpod: ^2.6.1
  share_plus: ^11.0.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # To add custom fonts to your application
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700



